name: Rocky 9

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rocky-9:
    uses: ./.github/workflows/reusable_distro_workflow.yml
    with:
      distro: "docker.io/library/rockylinux:9-minimal"
      package_man: "dnf"
